"""increase normalized_fees symbol column to varchar 256

Revision ID: 0a23a23c0e6e
Revises: 7929d0d7b00f
Create Date: 2026-03-02 18:36:11.852412
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a23a23c0e6e'
down_revision: Union[str, None] = '7929d0d7b00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('normalized_fees', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('normalized_fees', 'symbol',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
