"""normalization_v2_expanded_schema

Revision ID: 399dcf56e054
Revises: 8988562bea56
Create Date: 2026-02-27 16:31:30.828869
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '399dcf56e054'
down_revision: Union[str, None] = '8988562bea56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Add new values to existing PostgreSQL enum types ---
    # ALTER TYPE ... ADD VALUE cannot run inside a transaction in PostgreSQL.
    # We commit the current transaction, run the enum additions, then start a new one.
    connection = op.get_bind()
    connection.execute(sa.text("COMMIT"))

    connection.execute(sa.text("ALTER TYPE participanttype ADD VALUE IF NOT EXISTS 'NON_CUSTOMER'"))
    connection.execute(sa.text("ALTER TYPE participanttype ADD VALUE IF NOT EXISTS 'ALL'"))

    connection.execute(sa.text("ALTER TYPE securityclass ADD VALUE IF NOT EXISTS 'SPY'"))
    connection.execute(sa.text("ALTER TYPE securityclass ADD VALUE IF NOT EXISTS 'QQQ'"))
    connection.execute(sa.text("ALTER TYPE securityclass ADD VALUE IF NOT EXISTS 'IWM'"))
    connection.execute(sa.text("ALTER TYPE securityclass ADD VALUE IF NOT EXISTS 'NDX'"))
    connection.execute(sa.text("ALTER TYPE securityclass ADD VALUE IF NOT EXISTS 'RUT'"))
    connection.execute(sa.text("ALTER TYPE securityclass ADD VALUE IF NOT EXISTS 'VIX'"))
    connection.execute(sa.text("ALTER TYPE securityclass ADD VALUE IF NOT EXISTS 'ALL'"))

    connection.execute(sa.text("ALTER TYPE ordertype ADD VALUE IF NOT EXISTS 'PIM'"))
    connection.execute(sa.text("ALTER TYPE ordertype ADD VALUE IF NOT EXISTS 'CROSSING'"))
    connection.execute(sa.text("ALTER TYPE ordertype ADD VALUE IF NOT EXISTS 'FLEX'"))
    connection.execute(sa.text("ALTER TYPE ordertype ADD VALUE IF NOT EXISTS 'OPENING'"))
    connection.execute(sa.text("ALTER TYPE ordertype ADD VALUE IF NOT EXISTS 'ROUTED'"))
    connection.execute(sa.text("ALTER TYPE ordertype ADD VALUE IF NOT EXISTS 'ALL'"))

    connection.execute(sa.text("ALTER TYPE feetype ADD VALUE IF NOT EXISTS 'CROSSING_FEE'"))
    connection.execute(sa.text("ALTER TYPE feetype ADD VALUE IF NOT EXISTS 'PIM_FEE'"))
    connection.execute(sa.text("ALTER TYPE feetype ADD VALUE IF NOT EXISTS 'RESPONSE_FEE'"))
    connection.execute(sa.text("ALTER TYPE feetype ADD VALUE IF NOT EXISTS 'BREAK_UP_REBATE'"))
    connection.execute(sa.text("ALTER TYPE feetype ADD VALUE IF NOT EXISTS 'SURCHARGE'"))
    connection.execute(sa.text("ALTER TYPE feetype ADD VALUE IF NOT EXISTS 'CANCELLATION'"))
    connection.execute(sa.text("ALTER TYPE feetype ADD VALUE IF NOT EXISTS 'STOCK_HANDLING'"))

    # Create the new feeunit enum type (doesn't exist yet in PostgreSQL)
    connection.execute(sa.text(
        "CREATE TYPE feeunit AS ENUM "
        "('PER_CONTRACT', 'PER_CONTRACT_SIDE', 'PER_SHARE', 'MONTHLY_FLAT', "
        "'PER_PORT_MONTHLY', 'PERCENTAGE', 'PER_ORDER')"
    ))

    connection.execute(sa.text("BEGIN"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('tier_group', sa.String(length=100), nullable=False),
    sa.Column('tier_number', sa.Integer(), nullable=False),
    sa.Column('tier_name', sa.String(length=200), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_retroactive', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['fee_schedule_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_tiers_exchange_id'), 'fee_tiers', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_fee_tiers_snapshot_id'), 'fee_tiers', ['snapshot_id'], unique=False)
    op.add_column('normalized_fees', sa.Column('fee_code', sa.String(length=20), nullable=True))
    # Reuse the existing participanttype enum for contra_party_type
    participanttype = postgresql.ENUM('CUSTOMER', 'PROFESSIONAL', 'MARKET_MAKER', 'AWAY_MARKET_MAKER', 'FIRM', 'BROKER_DEALER', 'NON_CUSTOMER', 'ALL', name='participanttype', create_type=False)
    op.add_column('normalized_fees', sa.Column('contra_party_type', participanttype, nullable=True))
    op.add_column('normalized_fees', sa.Column('symbol', sa.String(length=20), nullable=True))
    feeunit = postgresql.ENUM('PER_CONTRACT', 'PER_CONTRACT_SIDE', 'PER_SHARE', 'MONTHLY_FLAT', 'PER_PORT_MONTHLY', 'PERCENTAGE', 'PER_ORDER', name='feeunit', create_type=False)
    op.add_column('normalized_fees', sa.Column('fee_unit', feeunit, server_default='PER_CONTRACT', nullable=False))
    op.add_column('normalized_fees', sa.Column('tier_id', sa.UUID(), nullable=True))
    op.add_column('normalized_fees', sa.Column('routing_destination', sa.String(length=200), nullable=True))
    op.add_column('normalized_fees', sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('normalized_fees', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('normalized_fees', sa.Column('section_ref', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'normalized_fees', 'fee_tiers', ['tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'normalized_fees', type_='foreignkey')
    op.drop_column('normalized_fees', 'section_ref')
    op.drop_column('normalized_fees', 'expiry_date')
    op.drop_column('normalized_fees', 'conditions')
    op.drop_column('normalized_fees', 'routing_destination')
    op.drop_column('normalized_fees', 'tier_id')
    op.drop_column('normalized_fees', 'fee_unit')
    op.drop_column('normalized_fees', 'symbol')
    op.drop_column('normalized_fees', 'contra_party_type')
    op.drop_column('normalized_fees', 'fee_code')
    op.drop_index(op.f('ix_fee_tiers_snapshot_id'), table_name='fee_tiers')
    op.drop_index(op.f('ix_fee_tiers_exchange_id'), table_name='fee_tiers')
    op.drop_table('fee_tiers')
    op.execute("DROP TYPE IF EXISTS feeunit")
    # ### end Alembic commands ###
