"""add discovery status to exchanges and discovery_logs table

Revision ID: 8988562bea56
Revises: a1b2c3d4e5f6
Create Date: 2026-02-27 12:27:18.811800
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8988562bea56'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_url', sa.String(length=500), nullable=True),
    sa.Column('selected_alternates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_DISCOVERED', 'DISCOVERED', 'FAILED', 'STALE', name='discoverystatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_logs_exchange_id'), 'discovery_logs', ['exchange_id'], unique=False)
    op.add_column('exchanges', sa.Column('discovery_status', sa.Enum('NOT_DISCOVERED', 'DISCOVERED', 'FAILED', 'STALE', name='discoverystatus'), server_default='NOT_DISCOVERED', nullable=False))
    op.add_column('exchanges', sa.Column('discovered_at', sa.DateTime(), nullable=True))
    op.add_column('exchanges', sa.Column('discovery_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('scraped_documents', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('scraped_documents', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scraped_documents', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scraped_documents', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('exchanges', 'discovery_metadata')
    op.drop_column('exchanges', 'discovered_at')
    op.drop_column('exchanges', 'discovery_status')
    op.drop_index(op.f('ix_discovery_logs_exchange_id'), table_name='discovery_logs')
    op.drop_table('discovery_logs')
    # ### end Alembic commands ###
