"""add exchange_profiles table

Revision ID: a224a46e5269
Revises: 399dcf56e054
Create Date: 2026-02-28 00:06:28.052532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a224a46e5269'
down_revision: Union[str, None] = '399dcf56e054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('table_mappings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('table_fingerprints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('LEARNING', 'ACTIVE', 'NEEDS_UPDATE', name='profilestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_profiles')
    # ### end Alembic commands ###
