"""initial schema

Revision ID: f40cf4538f9a
Revises: 
Create Date: 2026-02-27 00:26:09.248341
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f40cf4538f9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('operator', sa.String(length=200), nullable=False),
    sa.Column('fee_schedule_url', sa.String(length=500), nullable=False),
    sa.Column('alternate_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fee_schedule_format', sa.Enum('PDF', 'HTML', 'EXCEL', name='feescheduleformat'), nullable=False),
    sa.Column('scraper_type', sa.Enum('HTTP', 'BROWSER', name='scrapertype'), nullable=False),
    sa.Column('parser_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchanges_code'), 'exchanges', ['code'], unique=True)
    op.create_table('subscribers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('exchanges_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='null = all exchanges, or list of exchange codes'),
    sa.Column('notification_frequency', sa.Enum('IMMEDIATE', 'DAILY_DIGEST', 'WEEKLY', name='notificationfrequency'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fee_schedule_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_document', sa.LargeBinary(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('ai_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_fees_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsing_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARSED', 'NORMALIZED', 'VERIFIED', 'FAILED', name='snapshotstatus'), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('milestone_tag', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_schedule_snapshots_exchange_id'), 'fee_schedule_snapshots', ['exchange_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscriber_id', sa.UUID(), nullable=False),
    sa.Column('fee_change_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_status', sa.Enum('SENT', 'FAILED', 'BOUNCED', name='deliverystatus'), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'NO_CHANGE', name='scrapestatus'), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('has_changes', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_logs_exchange_id'), 'scrape_logs', ['exchange_id'], unique=False)
    op.create_table('fee_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('old_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('new_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.Enum('NEW', 'MODIFIED', 'REMOVED', name='changetype'), nullable=False),
    sa.Column('participant_type', sa.Enum('CUSTOMER', 'PROFESSIONAL', 'MARKET_MAKER', 'AWAY_MARKET_MAKER', 'FIRM', 'BROKER_DEALER', name='participanttype'), nullable=True),
    sa.Column('security_class', sa.Enum('PENNY', 'NON_PENNY', 'INDEX', 'ETF', 'EQUITY', 'MINI', name='securityclass'), nullable=True),
    sa.Column('order_type', sa.Enum('SIMPLE', 'COMPLEX', 'AUCTION', 'DIRECTED', 'QCC', name='ordertype'), nullable=True),
    sa.Column('fee_type', sa.Enum('MAKER', 'TAKER', 'ROUTING', 'ORF', 'TRANSACTION', 'CLEARING', 'CONNECTIVITY', 'MARKET_DATA', 'MEMBERSHIP', name='feetype'), nullable=True),
    sa.Column('old_amount_cents', sa.Integer(), nullable=True),
    sa.Column('new_amount_cents', sa.Integer(), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.ForeignKeyConstraint(['new_snapshot_id'], ['fee_schedule_snapshots.id'], ),
    sa.ForeignKeyConstraint(['old_snapshot_id'], ['fee_schedule_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_changes_exchange_id'), 'fee_changes', ['exchange_id'], unique=False)
    op.create_table('normalized_fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('exchange_id', sa.UUID(), nullable=False),
    sa.Column('participant_type', sa.Enum('CUSTOMER', 'PROFESSIONAL', 'MARKET_MAKER', 'AWAY_MARKET_MAKER', 'FIRM', 'BROKER_DEALER', name='participanttype'), nullable=False),
    sa.Column('security_class', sa.Enum('PENNY', 'NON_PENNY', 'INDEX', 'ETF', 'EQUITY', 'MINI', name='securityclass'), nullable=False),
    sa.Column('order_type', sa.Enum('SIMPLE', 'COMPLEX', 'AUCTION', 'DIRECTED', 'QCC', name='ordertype'), nullable=False),
    sa.Column('fee_type', sa.Enum('MAKER', 'TAKER', 'ROUTING', 'ORF', 'TRANSACTION', 'CLEARING', 'CONNECTIVITY', 'MARKET_DATA', 'MEMBERSHIP', name='feetype'), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False, comment='Fee in hundredths of a cent for precision'),
    sa.Column('is_rebate', sa.Boolean(), nullable=False),
    sa.Column('volume_tier', sa.String(length=100), nullable=True),
    sa.Column('tier_threshold_pct', sa.Float(), nullable=True),
    sa.Column('tier_threshold_contracts', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['fee_schedule_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_fees_exchange_id'), 'normalized_fees', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_normalized_fees_snapshot_id'), 'normalized_fees', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_fees_snapshot_id'), table_name='normalized_fees')
    op.drop_index(op.f('ix_normalized_fees_exchange_id'), table_name='normalized_fees')
    op.drop_table('normalized_fees')
    op.drop_index(op.f('ix_fee_changes_exchange_id'), table_name='fee_changes')
    op.drop_table('fee_changes')
    op.drop_index(op.f('ix_scrape_logs_exchange_id'), table_name='scrape_logs')
    op.drop_table('scrape_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_fee_schedule_snapshots_exchange_id'), table_name='fee_schedule_snapshots')
    op.drop_table('fee_schedule_snapshots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_exchanges_code'), table_name='exchanges')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
